chore: add resource requests/limits to harbor
flanksource/karina pull request #784
Opened 2021-03-24 12:39 UTC by paddatrapper

Fixes: #770

2021-03-24 15:18 UTC, moshloop requested changes
Can we set minimum requests to 100m/200m cpu and 64/128Mi mem ?
Then when increasing them go in intervals of  

CPU: 100,200,500,1000,1500,2000
Mem: 64,128,256,512,1Gb,2gb,4gb etc..

Clair I think will need to burst to 1000m
Core and Registry cpu should be 200/500 and mem, 256/512
Registryctl can remain low 


e.g. 
clair

2021-03-25 09:05 UTC, moshloop commented on manifests/harbor/exporter.yaml
> +              cpu: 500m
```suggestion
              cpu: 200m
```

2021-03-25 14:11 UTC, moshloop requested changes
please check failing tests

2021-03-29 18:11 UTC, moshloop requested changes
I think we might need to reduce the requests for the test run in https://github.com/flanksource/karina/blob/master/test/patch1.yaml as we are limited to 7GB of memory total

2021-03-30 19:39 UTC, moshloop requested changes
So the requests/limits should have remained in manifests/harbor and then those new default requests should have been overridden in patch1, bring down the requirements for tests

2021-04-01 21:42 UTC, moshloop commented
@paddatrapper  can you check the failing harbor test ?

2021-04-06 14:28 UTC, paddatrapper commented
Harbor is now passing

2021-04-07 07:53 UTC, merged